version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      # Database connection
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      # Keycloak specific settings
      KC_HOSTNAME: keycloak.example.com  # Replace with your public domain
      KC_PROXY: edge  # This tells Keycloak it's behind a reverse proxy
      KC_HTTP_ENABLED: 'true'  # Enable HTTP because Nginx will handle HTTPS
      KC_HTTPS_PORT: 8080      # You can keep Keycloak listening on HTTP internally
    ports:
      - "8080:8080"  # Expose HTTP port, Nginx will handle SSL on port 443
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
